server {
    listen 80;

    location /api/proxy/emu/ {
        proxy_pass         http://redfish-emu:8008/;
        proxy_redirect     off;
        proxy_set_header   Host $proxy_host;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 3600s;
    }

    location /api/proxy/ras-emu/ {
        proxy_pass         http://redfish-ras-emu:8009/;
        proxy_redirect     off;
        proxy_set_header   Host $proxy_host;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 3600s;
    }

    location / {
        root  /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
